### ISSUE TITLE
replace `updates_made` logic

### ISSUE THREAD

**Issue by fgregg** [datamade/la-metro-councilmatic#509] opened 2019-11-18 21:16 UTC
Currently, we have logic to show an "updated_tag" if an event has been updated more recently than the event's agenda.

This logic is going to be a bit difficult to reproduce exactly with the 2.5 models. 

I wonder if if would be acceptable to show a tag that indicated that an event had been updated, in any way, within some time window.

For example, if an upcoming event had been updated in any way (changed time, address, document, agenda item, etc), in the past two or three days, then show the "Updated" tag.

Thoughts, @shrayshray ?

**Comment by shrayshray** [comment] 2019-11-19 21:00
"Currently, we have logic to show an "updated_tag" if an event has been updated more recently than the event's agenda." Updated more recently than the Agenda *date*, or updated since the Agenda was *posted/published*?
Does the current logic only show the "updated_tag" up until the meeting date? I was looking for an example on the Events page and didn't see any which had the tag, other than the meetings with Agendas posted last Friday.

**Comment by fgregg** [comment] 2019-11-19 22:01
updated since the agenda was inserted into our system, which is going to be close to when the agenda was posted/published"

The current logic shows the updated_tag whenever this condition is met, even, possibly for past events.

**Comment by shrayshray** [comment] 2019-11-19 22:41
Okay, then yes, let's go with the logic of:
If an upcoming event had been updated in any way (changed time, address, document, agenda item, status, etc), in the past **three** days, then show the "Updated" tag.

**Comment by fgregg** [comment] 2019-11-19 23:12
perfect, thanks!

**Comment by hancush** [comment] 2020-02-25 19:22
This is done and available on the test site. https://lametro-upgrade.datamade.us

**Comment by shrayshray** [comment] 2020-03-11 23:39
#566 may be caused by me not articulating the logic for displaying the "Updated" tag clearly enough in this thread. The logic should be:
1. Check whether the Agenda has been published. If no, skip. If yes:
2. If it has been updated in any way (changed time, address, document, agenda item, status, etc.), within 3 days _after being published_ then show the "Updated" tag.

**Comment by hancush** [comment] 2020-03-12 16:03
Hi, @shrayshray. 

The pieces we have to work with are the date (but not the time) the agenda was published, and the date and time the event was last updated. 

Events are updated when an agenda is published, so if we compare the agenda date with the event updated date, every event will be marked as "updated" when an agenda is published. 

We could do something like if an event is updated within three days of the agenda being published, _not including the day it's published_. Would that work?

**Comment by hancush** [comment] 2020-03-12 16:34
@shrayshray There are some further caveats to using the agenda publishing date, chiefly that we aren't sure it's updated when an agenda is changed from private to public. So, any approach that makes use of the publishing date, including the one I suggested in my last comment, has the potential to behave differently than expected because the date is not reliable. 

Is there acceptable logic that does not use the agenda publishing date?

**Comment by shrayshray** [comment] 2020-03-19 01:07
@hancush I have an idea to avoid using the publishing date. What if we looked for updates within 96 hours before the meeting start time? This is enough to get us out of the zone for Friday posting to trigger "Updated" for both Wednesday and Thursday meetings. It's an extremely rare case for updates to be made on Saturday or Sunday; and any edited Report clearly reads "Revised" or "Withdrawn" on the Agenda and Report itself if a change is made during _any_ period of time.

Does looking back 96 hours prior to the meeting start time for updates sound feasible?

**Comment by hancush** [comment] 2020-03-19 20:36
@shrayshray That sounds reasonable to me!

**Comment by hancush** [comment] 2020-03-20 15:50
I've implemented this logic and deployed it to the test site, @shrayshray!

**Comment by shrayshray** [comment] 2020-03-20 20:38
@hancush great! Will keep an eye on it when next month's Agendas are posted and if any changes are made to them before the meeting.

**Closed** 2020-04-02 21:17 UTC
Labels: 2.5
