### ISSUE TITLE
9/28/17 Board of Directors Meeting Missing

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#254] opened 2018-02-14 01:17 UTC
The 9/28/17 Board of Directors  meeting is not showing up on the site. It's not listed on the Meetings page, and the link in the side bar here goes to an error page: https://boardagendas.metro.net/board-members/
Here it is on the Legistar site: https://metro.legistar.com/MeetingDetail.aspx?ID=549047&GUID=74452B78-CEAA-4399-AE3C-D02A1B48B7D1&Options=info&Search=

**Comment by reginafcompton** [comment] 2018-02-14 16:13
We've resolve this issue: https://boardagendas.metro.net/event/regular-board-meeting-41afe91b68f7/

The root cause of it has to do with the problem outlined here: https://github.com/datamade/la-metro-councilmatic/issues/233.

I'll close this issue. @shrayshray - let's discuss prioritizing issue #233 for our next milestone.

**Closed by reginafcompton** 2018-02-14 16:13 UTC
