### ISSUE TITLE
Board Report: Minutes not showing related reports other than Minutes

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#669] opened 2020-11-11 19:40 UTC
We started relating to Minutes all the reports which were acted on in that meeting and accounted for in the Minutes, and the Minutes approved in those Minutes (previous meeting) and the Minutes which approved these Minutes (next meeting).
For some reason, the reports related to the Minutes aren't showing - only the reports which type = Minutes show. Here is an example of this issue: https://boardagendas.metro.net/board-report/2019-0454/

Here's an example of where its working correctly (all related reports are showing): https://boardagendas.metro.net/board-report/2020-0714/

**Comment by fatima3558** [comment] 2020-12-17 15:29
Hi @shrayshray! @hancush and I took a look at what was going on here, and it looks like we have some logic in the legistar scraper that results us only getting the matter relations with the highest value for the `MatterRelationFlag` property in legistar. 

Here's the legistar matter info for the bill you linked to in this issue where the `related_bill`s show up as expected: http://webapi.legistar.com/v1/metro/matters/7156/relations

And the matter info for the bill where the `related_bill`s are *not* showing up as expected: http://webapi.legistar.com/v1/metro/matters/6008/relations

Is there a way to set all of the matter relations to have the same value for this flag?

**Comment by hancush** [comment] 2021-01-06 21:43
@camachoo will look into how the matter relation flag is set. In the meantime, we will revise the Legistar scraper to grab all relations. We'll see how many duplicates (if any?) this causes.

**Comment by hancush** [comment] 2021-01-12 14:47
Related issue: https://github.com/datamade/la-metro-councilmatic/issues/227

PRs:

- https://github.com/opencivicdata/scrapers-us-municipal/pull/169
- https://github.com/opencivicdata/python-legistar-scraper/pull/47

**Comment by hancush** [comment] 2021-01-12 17:53
I just deployed a change to the Legistar scraper that should capture all related board reports. Will check on this tomorrow (after the full scrape overnight) to confirm that all attachments have come through for https://boardagendas.metro.net/board-report/2019-0454/.

**Comment by hancush** [comment] 2021-01-13 17:03
The scraper change wasn't captured in our scraper image due to Docker build caching. I resolved this in https://github.com/datamade/scrapers-us-municipal/pull/60 and confirmed the image contains the latest version of the scraper. Keeping my eyeballs peeled for these attachments to come through overnight tonight.

**Comment by hancush** [comment] 2021-01-14 20:30
@shrayshray Behold! Attachments have come through: https://boardagendas.metro.net/board-report/2019-0454/

Want to spot check a few other minutes files to ensure the fix repaired attachments more broadly?

**Comment by shrayshray** [comment] 2021-01-14 23:34
@hancush I spot checked about 10 and they all look good - thank you!!

**Comment by hancush** [comment] 2021-02-03 21:14
The correct relation is not always the max. Some chairs submit blank cover, then update previous version. Regina implemented a way to identify which version is the active version. I'll open a separate issue to check this, and close this.

**Comment by hancush** [comment] 2021-03-02 15:17
Opened a separate issue about detecting the active version. For our purposes, we're only using the version [to generate a distinct list of matter IDs from which to build relations](https://github.com/datamade/scrapers-us-municipal/blob/349f374a59e769248462bf818e9f4d85e5bc0662/lametro/bills.py#L277-L291). From that list, we capture matter file ID and intro date (in order to determine the legislative session it belongs to). @shrayshray, @camachoo – do either of these pieces of information vary between versions of a matter?

**Comment by shrayshray** [comment] 2021-03-03 20:12
@hancush No. The matter file ID and intro date would be consistent across versions of a matter.

**Comment by hancush** [comment] 2021-03-05 19:09
I will look up how we are handling getting the correct version at the board report level and update this thread. If it's capturing the correct version, then we can close this.

**Comment by hancush** [comment] 2021-03-08 21:02
We use the `MatterVersion` attribute of an API Matter to determine which version of the text to retrieve.

Relevant links:

- https://github.com/datamade/la-metro-councilmatic/issues/237
- https://github.com/opencivicdata/python-legistar-scraper/pull/82 

@shrayshray This approach seems to be working as expected. I think it's safe to close this!

**Closed** 2021-04-06 20:03 UTC
Labels: question
