### ISSUE TITLE
Board Reports: Recent Reports not showing in search

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#534] opened 2020-01-15 23:33 UTC
It looks there there might be an issue with indexing of reports on the [Board Reports search page](https://boardagendas.metro.net/search/). Upon entering the page, the most recent reports listed are from 10/24/19. And when I search for reports on agendas more recently than 10/24/19, they're not retrieved. 
For example, [2019-0817](https://boardagendas.metro.net/board-report/2019-0817/) was on the agenda for the [1/15/2020 Planning and Programming Committee meeting](https://boardagendas.metro.net/event/planning-and-programming-committee-61e07ee32be9/). The link to it in the sidebar of the meeting page works and takes me to the [report page](https://boardagendas.metro.net/board-report/2019-0817/). 
But when I search for 2019-0817 from the homepage or search page, it's not retrieved. And of the 818 board reports retrieved on the query, none are dated more recently than 10/24/19.

**Comment by hancush** [comment] 2020-01-16 18:10
Hi, @shrayshray. It looks like updates to the production search index have been failing. I opened an issue to ensure we're alerted when failures occur. Meanwhile, I'm working on a resolution for the current failures, which are being caused by insufficient memory for updates. Strangely, this is not affecting the staging search index. It's also unclear to me why we didn't run into this issue sooner. Will advise ASAP.

**Comment by shrayshray** [comment] 2020-01-16 19:23
okay, thank you for the update!

**Comment by hancush** [comment] 2020-01-16 20:15
@shrayshray We restarted the search engine, which freed up sufficient memory to accept new updates. 🎊 Looks like 2019-0817 is now in the search index! 

A check we put in place to verify that the index contains records for each board report indicates that we've gotten all the reports, but would you mind checking a few more recent reports to confirm things look as expected? In the meantime, I'll open an issue to track the mysterious memory problem in the longer term.

**Comment by shrayshray** [comment] 2020-01-16 20:45
@hancush, just went to check the reports as requested in your comment, and saw weird double meetings documented in #536 can we pivot to that issue?

**Comment by hancush** [comment] 2020-01-16 21:12
@shrayshray Sure thing!

**Comment by shrayshray** [comment] 2020-01-16 21:56
These reports are all showing up as expected via search, but not when filtering by meeting body, as noted in #537

**Comment by hancush** [comment] 2020-01-16 22:37
Thanks for your help, @shrayshray. Since we've resolved the immediate issue, I'm going to close this in lieu of #535 and #538. Taking a look at #537 now.

**Closed by hancush** 2020-01-16 22:38 UTC
Labels: bug
