### ISSUE TITLE
Board Reports search page: Missing [most recent action] on upgrade test site

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#555] opened 2020-02-26 22:13 UTC
The most recent action is missing from reports listed in the search results on the upgrade test site.

On boardagendas.metro.net:
![image](https://user-images.githubusercontent.com/28063988/75392905-dbde9d80-58a1-11ea-9a01-fa223ae4a83c.png)

On lametro-upgrade.datamade.us:
![image](https://user-images.githubusercontent.com/28063988/75392810-a6d24b00-58a1-11ea-94d5-f2db5faf9735.png)

**Comment by shrayshray** [comment] 2020-02-26 23:45
Related to #553?

**Comment by hancush** [comment] 2020-03-11 19:12
Indeed, this was related to #553! 

The short version of the issue is that we were only generating a last action date when a board report was updated, not when it was created. This problem was resolved via https://github.com/opencivicdata/pupa/pull/329 and https://github.com/datamade/django-councilmatic/pull/265.

<img width="930" alt="Screen Shot 2020-03-11 at 2 08 18 PM" src="https://user-images.githubusercontent.com/12176173/76454194-34ce2b80-63a2-11ea-91c5-e243cb46da52.png">

Are last action dates looking good for search results now, @shrayshray?

**Comment by shrayshray** [comment] 2020-03-11 21:23
@hancush yes, looks good now!

**Closed** 2020-04-02 21:17 UTC
Labels: 2.5
